# %% [markdown]
# ## Step 1: Environment Initialization and the Baseline Illusion
# Import all required analytical libraries and load the synthetic Nvidia AI Capex dataset.
# Construct a naive baseline OLS regression predicting AI Software Revenue.
# Observe the deceptively high R-squared and the extremely low p-values.
# Document this baseline state of apparent "perfection."

# %%
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import statsmodels.api as sm
from statsmodels.stats.diagnostic import het_white
from statsmodels.stats.outliers_influence import variance_inflation_factor
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

# Step 1: Ingestion and Naive Baseline Model
df = pd.read_csv(Path(__file__).parent.parent / 'Data' /'Nvidia_AI_Capex_Diagnostics_2026.csv')


formula = 'AI_Software_Revenue ~ Hardware_Capex + Cloud_GPU_Deployments'
baseline_model = smf.ols(formula, data=df).fit()

print("--- NAIVE BASELINE OLS MODEL ---")
print(baseline_model.summary())
# %%
# Step 2: Visual Forensics
fitted_vals = baseline_model.fittedvalues
residuals = baseline_model.resid

plt.figure(figsize=(10, 6))
sns.scatterplot(x=fitted_vals, y=residuals, alpha=0.6, color='darkred')
plt.axhline(0, color='black', linestyle='--', linewidth=2)
plt.title('Visual Forensics: Residuals vs Fitted Values (Checking for Heteroscedasticity)')
plt.xlabel('Fitted Values (Predicted AI Revenue)')
plt.ylabel('Residual Errors')
plt.show()

# %% [markdown]
# ## Step 3: Formalizing the Diagnosis (The White Test)
# Visual forensics must be corroborated by rigorous mathematical testing.
# Execute the White Test by passing the model's residuals and the model's exact design matrix
# into the function to statistically confirm if variance is a function of the predictors.

# %%
# Step 3: The White Test Execution
# We must extract the design matrix generated by the formula interface
exog_matrix = baseline_model.model.exog
white_test_results = het_white(baseline_model.resid,exog_matrix)

labels = ['LM Statistic', 'LM-Test p-value', 'F-Statistic', 'F-Test p-value']
print("\n--- WHITE TEST RESULTS ---")
print(dict(zip(labels, white_test_results)))

# %% [markdown]
# ## Step 4: Diagnosing Multicollinearity (Variance Inflation Factor)
# Construct a Python for-loop to iterate through the columns of your design matrix
# and calculate the VIF for every explanatory variable to detect if redundant data
# is artificially inflating the variance of your coefficients.

# %%
# Step 4: Variance Inflation Factor (VIF) Loop
print("\n--- VARIANCE INFLATION FACTORS ---")

# Start loop at 1 to skip the constant intercept column at index 0
for i in range(1, exog_matrix.shape[1]):
    vif = variance_inflation_factor(exog_matrix, i)
    print(f"VIF for variable {i}: {vif:.2f}")

# %% [markdown]
# ## Step 5: The Mathematical Correction (HC3 Standard Errors)
# Re-fit the exact same OLS formula from Step 1, but this time apply the
# Heteroscedasticity-Consistent (HC3) robust matrix correction to rescue the model
# and reveal the true, conservative statistical significance thresholds.

# %%
# Step 5: The Correction - HC3 Robust Standard Errors
robust_model = smf.ols(formula, data=df).fit(cov_type="HC3")

print("\n--- ROBUST OLS MODEL (HC3) ---")
print(robust_model.summary())

# %% [markdown]
# ## Step 6: Interactive Diagnostic Dashboard
# Create interactive visualizations for model comparison, heteroscedasticity diagnostics,
# multicollinearity analysis (VIF), and residual exploration.
# Works natively in Jupyter, or run as Python script to generate HTML visualizations.

# %%
import plotly.graph_objects as go
import plotly.express as px
from scipy import stats

print("\n--- STEP 6: INTERACTIVE DIAGNOSTIC DASHBOARD ---")
print("Generating interactive visualizations with Plotly...")

# ============================================================================
# DASHBOARD 1: RESIDUALS VS FITTED VALUES (Interactive)
# ============================================================================
# Interactive scatter plot with color-coded residual magnitude and reference line.
# Hover to see exact values. Zoom and pan to explore outliers.
fitted_vals_dashboard = baseline_model.fittedvalues
residuals_dashboard = baseline_model.resid

fig_resid_fitted = go.Figure()

# Add scatter trace with color scale
fig_resid_fitted.add_trace(go.Scatter(
    x=fitted_vals_dashboard,
    y=residuals_dashboard,
    mode='markers',
    marker=dict(
        size=np.abs(residuals_dashboard) * 5,  # Size by residual magnitude
        color=np.abs(residuals_dashboard),
        colorscale='Viridis',
        showscale=True,
        colorbar=dict(title="Abs(Residual)"),
        opacity=0.6,
        line=dict(width=0.5)
    ),
    text=[f"Fitted: {x:.3f}<br>Residual: {y:.3f}" for x, y in zip(fitted_vals_dashboard, residuals_dashboard)],
    hovertemplate='%{text}<extra></extra>'
))

# Add zero-line reference
fig_resid_fitted.add_hline(
    y=0,
    line_dash="dash",
    line_color="red",
    annotation_text="Zero Residual Reference",
    annotation_position="right"
)

fig_resid_fitted.update_layout(
    title="Residuals vs Fitted Values (Interactive Exploration)",
    xaxis_title="Fitted Values (Predicted AI Revenue)",
    yaxis_title="Residual Errors",
    height=600,
    width=1000,
    hovermode='closest',
    template='plotly_white'
)

print("  ✓ Residuals vs Fitted Values plot generated")

# ============================================================================
# DASHBOARD 2: RESIDUAL DISTRIBUTION & NORMALITY CHECK
# ============================================================================
# Histogram with overlaid normal distribution curve
fig_resid_hist = go.Figure()

# Create histogram bins
hist_counts, hist_bins = np.histogram(residuals_dashboard, bins=30)
bin_centers = (hist_bins[:-1] + hist_bins[1:]) / 2

# Add histogram
fig_resid_hist.add_trace(go.Bar(
    x=bin_centers,
    y=hist_counts,
    name='Residuals',
    marker=dict(color='steelblue', opacity=0.7),
    width=hist_bins[1] - hist_bins[0]
))

# Overlay normal distribution
mean_resid = residuals_dashboard.mean()
std_resid = residuals_dashboard.std()
x_range = np.linspace(residuals_dashboard.min(), residuals_dashboard.max(), 100)
normal_curve = (len(residuals_dashboard) / 30) * std_resid * \
               (1 / (std_resid * np.sqrt(2 * np.pi))) * \
               np.exp(-0.5 * ((x_range - mean_resid) / std_resid) ** 2)

fig_resid_hist.add_trace(go.Scatter(
    x=x_range,
    y=normal_curve,
    mode='lines',
    name='Theoretical Normal',
    line=dict(color='red', width=3)
))

fig_resid_hist.update_layout(
    title="Distribution of Residuals with Normal Curve Overlay",
    xaxis_title="Residual Value",
    yaxis_title="Frequency",
    height=500,
    width=900,
    hovermode='x unified',
    barmode='overlay',
    template='plotly_white'
)

print("  ✓ Residual distribution plot generated")

# ============================================================================
# DASHBOARD 3: Q-Q PLOT (Normality Assessment)
# ============================================================================
# Quantile-Quantile plot: points should follow red line if residuals are normal
quantiles = stats.probplot(residuals_dashboard, dist="norm")

fig_qq = go.Figure()

# Add sample quantiles vs theoretical quantiles
fig_qq.add_trace(go.Scatter(
    x=quantiles[0][0],
    y=quantiles[0][1],
    mode='markers',
    name='Residual Quantiles',
    marker=dict(size=8, color='steelblue', opacity=0.6)
))

# Add theoretical normal line
line_x = np.array([quantiles[0][0].min(), quantiles[0][0].max()])
line_y = quantiles[1][1] + quantiles[1][0] * line_x
fig_qq.add_trace(go.Scatter(
    x=line_x,
    y=line_y,
    mode='lines',
    name='Theoretical Normal Line',
    line=dict(color='red', width=3)
))

fig_qq.update_layout(
    title="Q-Q Plot: Assessment of Normality",
    xaxis_title="Theoretical Quantiles (Normal Distribution)",
    yaxis_title="Sample Quantiles (Residuals)",
    height=500,
    width=900,
    hovermode='closest',
    template='plotly_white'
)

print("  ✓ Q-Q plot generated")

# ============================================================================
# DASHBOARD 4: VIF SCORES MULTICOLLINEARITY CHECK
# ============================================================================
# Bar chart with warning thresholds for multicollinearity
exog_matrix_dashboard = baseline_model.model.exog
var_names = baseline_model.model.exog_names

vif_scores = []
for i in range(1, exog_matrix_dashboard.shape[1]):  # Skip intercept
    vif = variance_inflation_factor(exog_matrix_dashboard, i)
    vif_scores.append({'Variable': var_names[i], 'VIF': vif})

vif_df_dashboard = pd.DataFrame(vif_scores)

# Create color list based on VIF thresholds
colors = ['green' if v < 5 else 'orange' if v < 10 else 'red' for v in vif_df_dashboard['VIF']]

fig_vif = go.Figure()

fig_vif.add_trace(go.Bar(
    x=vif_df_dashboard['Variable'],
    y=vif_df_dashboard['VIF'],
    marker=dict(color=colors, opacity=0.7),
    text=vif_df_dashboard['VIF'].round(2),
    textposition='outside',
    hovertemplate='<b>%{x}</b><br>VIF: %{y:.2f}<extra></extra>'
))

# Add threshold lines
fig_vif.add_hline(y=5, line_dash="dash", line_color="orange",
                  annotation_text="Moderate Threshold (VIF=5)")
fig_vif.add_hline(y=10, line_dash="dash", line_color="red",
                  annotation_text="Critical Threshold (VIF=10)")

fig_vif.update_layout(
    title="Variance Inflation Factor (VIF) by Variable",
    xaxis_title="Variable",
    yaxis_title="VIF Score",
    height=500,
    width=900,
    showlegend=False,
    hovermode='x unified',
    template='plotly_white'
)

print("  ✓ VIF multicollinearity plot generated")

# ============================================================================
# DASHBOARD 5: WHITE TEST COMPARISON VISUALIZATION
# ============================================================================
# Visualize White Test results
white_test_vals = het_white(baseline_model.resid, exog_matrix_dashboard)
lm_stat, lm_pval, f_stat, f_pval = white_test_vals

fig_white = go.Figure()

# Add bars for LM and F test p-values
fig_white.add_trace(go.Bar(
    x=['LM Test', 'F Test'],
    y=[lm_pval, f_pval],
    marker=dict(
        color=['red' if p < 0.05 else 'green' for p in [lm_pval, f_pval]],
        opacity=0.7
    ),
    text=[f'{lm_pval:.4f}', f'{f_pval:.4f}'],
    textposition='outside',
    name='p-value'
))

# Add significance threshold line
fig_white.add_hline(
    y=0.05,
    line_dash="dash",
    line_color="black",
    annotation_text="Significance Level (α=0.05)",
    annotation_position="right"
)

fig_white.update_layout(
    title="White Test for Heteroscedasticity (Interactive)",
    yaxis_title="p-value",
    height=400,
    width=700,
    showlegend=False,
    hovermode='x unified',
    template='plotly_white',
    yaxis=dict(range=[0, 1])
)

# Add interpretation text
if lm_pval < 0.05 or f_pval < 0.05:
    fig_white.add_annotation(
        text="⚠️ Heteroscedasticity Detected (p < 0.05)<br>Use HC3 Robust Standard Errors",
        xref="paper", yref="paper",
        x=0.5, y=-0.3,
        showarrow=False,
        bgcolor="rgba(255,200,0,0.2)",
        bordercolor="orange",
        borderwidth=2
    )
else:
    fig_white.add_annotation(
        text="✓ No Strong Evidence of Heteroscedasticity (p ≥ 0.05)",
        xref="paper", yref="paper",
        x=0.5, y=-0.3,
        showarrow=False,
        bgcolor="rgba(0,200,100,0.2)",
        bordercolor="green",
        borderwidth=2
    )

print("  ✓ White test visualization generated")

# ============================================================================
# DASHBOARD 6: MODEL COMPARISON (Naive vs HC3)
# ============================================================================
# Side-by-side comparison of coefficients with confidence intervals
coef_comparison = pd.DataFrame({
    'Variable': baseline_model.params.index,
    'Naive OLS': baseline_model.params.values,
    'HC3 Robust': robust_model.params.values,
    'SE Naive': baseline_model.bse.values,
    'SE Robust': robust_model.bse.values
})

fig_coef = go.Figure()

# Naive OLS coefficients with error bars
fig_coef.add_trace(go.Bar(
    x=coef_comparison['Variable'],
    y=coef_comparison['Naive OLS'],
    error_y=dict(
        type='data',
        array=1.96 * coef_comparison['SE Naive'],  # 95% CI
        visible=True
    ),
    name='Naive OLS',
    marker=dict(color='steelblue', opacity=0.7)
))

# HC3 Robust coefficients with error bars
fig_coef.add_trace(go.Bar(
    x=coef_comparison['Variable'],
    y=coef_comparison['HC3 Robust'],
    error_y=dict(
        type='data',
        array=1.96 * coef_comparison['SE Robust'],  # 95% CI
        visible=True
    ),
    name='HC3 Robust',
    marker=dict(color='seagreen', opacity=0.7)
))

fig_coef.add_hline(y=0, line_dash="dash", line_color="black")
fig_coef.update_layout(
    title="Coefficient Comparison: Naive OLS vs HC3 Robust (with 95% CI)",
    yaxis_title="Coefficient Value",
    barmode='group',
    height=500,
    width=1000,
    hovermode='x unified',
    template='plotly_white'
)

print("  ✓ Model comparison plot generated")

# ============================================================================
# DISPLAY & EXPORT VISUALIZATIONS
# ============================================================================
print("\n✓ All interactive visualizations created successfully!")
print("\nTo view the plots:")
print("  - In Jupyter: Run this cell to display plots inline")
print("  - In Python: Plots will be saved as HTML files")

# Display in Jupyter (if running in Jupyter)
try:
    from IPython.display import display
    print("\nDisplaying interactive plots...\n")
    display(fig_resid_fitted)
    display(fig_resid_hist)
    display(fig_qq)
    display(fig_vif)
    display(fig_white)
    display(fig_coef)
except ImportError:
    # Not in Jupyter; save as HTML files
    output_dir = Path(__file__).parent

    fig_resid_fitted.write_html(output_dir / "01_residuals_vs_fitted.html")
    fig_resid_hist.write_html(output_dir / "02_residual_distribution.html")
    fig_qq.write_html(output_dir / "03_qq_plot.html")
    fig_vif.write_html(output_dir / "04_vif_analysis.html")
    fig_white.write_html(output_dir / "05_white_test.html")
    fig_coef.write_html(output_dir / "06_model_comparison.html")

    print("\n📊 HTML visualizations saved to Lab14/:")
    print("   - 01_residuals_vs_fitted.html")
    print("   - 02_residual_distribution.html")
    print("   - 03_qq_plot.html")
    print("   - 04_vif_analysis.html")
    print("   - 05_white_test.html")
    print("   - 06_model_comparison.html")
    print("\nOpen any HTML file in your browser to interact with the plots.")

# %%
